#Ler um número qualquer e mostrar a sua tabuada
n = int(input('Ver a tabuada do nº:'))
print('Adição:')
print('{}+1 ='.format(n), n+1)
print('{}+2 ='.format(n), n+2)
print('{}+3 ='.format(n), n+3)
print('{}+4 ='.format(n), n+4)
print('{}+5 ='.format(n), n+5)
print('{}+6 ='.format(n), n+6)
print('{}+7 ='.format(n), n+7)
print('{}+8 ='.format(n), n+8)
print('{}+9 ='.format(n), n+9)
print('{}+10 ='.format(n), n+10)

print('Subtração:')
print('{}-1 ='.format(n), n-1)
print('{}-2 ='.format(n), n-2)
print('{}-3 ='.format(n), n-3)
print('{}-4 ='.format(n), n-4)
print('{}-5 ='.format(n), n-5)
print('{}-6 ='.format(n), n-6)
print('{}-7 ='.format(n), n-7)
print('{}-8 ='.format(n), n-8)
print('{}-9 ='.format(n), n-9)
print('{}-10 ='.format(n), n-10)

print('Multiplicação:')
print('{}x1 ='.format(n), n*1)
print('{}x2 ='.format(n), n*2)
print('{}x3 ='.format(n), n*3)
print('{}x4 ='.format(n), n*4)
print('{}x5 ='.format(n), n*5)
print('{}x6 ='.format(n), n*6)
print('{}x7 ='.format(n), n*7)
print('{}x8 ='.format(n), n*8)
print('{}x9 ='.format(n), n*9)
print('{}x10 ='.format(n), n*10)

print('Divisão:')
print('{}/1 ='.format(n), n/1)
print('{}/2 ='.format(n), n/2)
print('{}/3 ='.format(n), n/3)
print('{}/4 ='.format(n), n/4)
print('{}/5 ='.format(n), n/5)
print('{}/6 ='.format(n), n/6)
print('{}/7 ='.format(n), n/7)
print('{}/8 ='.format(n), n/8)
print('{}/9 ='.format(n), n/9)
print('{}/10 ='.format(n), n/10)

